#!/usr/bin/env python3
"""Bundle GROK_SYSTEM_PROMPT.md into src/server/DefaultSystemPrompt.hpp.

GROK_SYSTEM_PROMPT.md is the canonical default system prompt. Same rule as
bundle-ui.py: the markdown file is the source of truth, but users installing
via apt won't have the workspace file on disk, so we also embed it into the
binary. Two consumers use the embedded copy:

  1. AgentEngine::buildUnifiedPrompt() — when no GROK_SYSTEM_PROMPT.md is
     found in the workspace, the agent falls back to the embedded default
     instead of the skeleton stub it used before.

  2. RoutesSystem — the /api/system/prompt/default endpoint and the
     /api/system/prompt/reset action, plus a first-run seeded
     `~/.avacli/blueprints/default.json` blueprint that wraps the prompt.

Re-run whenever GROK_SYSTEM_PROMPT.md changes. build.sh and
packaging/deploy-to-packages.sh invoke this automatically; CMake has a
custom command that fires on edits to GROK_SYSTEM_PROMPT.md.

The raw string literal is split into <16380-char chunks for MSVC via
split_embedded_strings.py (same helper as bundle-ui.py).
"""

import json
import os
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
PROMPT_SRC = os.path.join(ROOT, 'GROK_SYSTEM_PROMPT.md')
OUT = os.path.join(ROOT, 'src', 'server', 'DefaultSystemPrompt.hpp')
SPLITTER = os.path.join(os.path.dirname(__file__), 'split_embedded_strings.py')

PROMPT_DELIM = 'avaprompt'
BP_DELIM = 'avabp'


def main():
    if not os.path.exists(PROMPT_SRC):
        sys.exit(f'ERROR: {PROMPT_SRC} not found')

    with open(PROMPT_SRC, 'r', encoding='utf-8') as f:
        prompt = f.read()

    if not prompt.strip():
        sys.exit(f'ERROR: {PROMPT_SRC} is empty')

    blueprint = {
        'name': 'Default Coding Agent',
        'description': (
            'The stock Avacli agent — full tool access, autonomous, '
            'coding-focused. Reset target for the System page.'
        ),
        'prompt': prompt,
        'nodes': [],
        'edges': [],
        'mermaid_src': '',
        'tools': [],
        'model_assignments': {},
        'is_default': True,
    }
    bp_json = json.dumps(blueprint, indent=2, ensure_ascii=False)

    for delim, payload, label in (
        (PROMPT_DELIM, prompt, 'prompt'),
        (BP_DELIM, bp_json, 'blueprint JSON'),
    ):
        if f'){delim}"' in payload:
            sys.exit(
                f'ERROR: embedded {label} contains the raw-string closer '
                f'"){delim}\""; pick a different delimiter in bundle-default-prompt.py.'
            )

    out = (
        '#pragma once\n'
        '#include <string>\n'
        '\n'
        '// AUTO-GENERATED by scripts/bundle-default-prompt.py.\n'
        '// Do not edit this file directly.\n'
        '// Edit GROK_SYSTEM_PROMPT.md and re-run scripts/bundle-default-prompt.py\n'
        '// (build.sh and packaging/deploy-to-packages.sh do this for you).\n'
        '\n'
        'namespace avacli {\n'
        '\n'
        '/// Full markdown text of the default system prompt, baked in\n'
        '/// at build time from GROK_SYSTEM_PROMPT.md.\n'
        'inline std::string getDefaultSystemPrompt() {\n'
        f'    return R"{PROMPT_DELIM}({prompt}){PROMPT_DELIM}";\n'
        '}\n'
        '\n'
        '/// Canonical "Default Coding Agent" blueprint as JSON text.\n'
        '/// Seeded into ~/.avacli/blueprints/default.json on first run\n'
        '/// and restored by POST /api/system/blueprints/reset.\n'
        'inline std::string getDefaultBlueprintJson() {\n'
        f'    return R"{BP_DELIM}({bp_json}){BP_DELIM}";\n'
        '}\n'
        '\n'
        '} // namespace avacli\n'
    )

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(out)

    subprocess.check_call([sys.executable, SPLITTER, OUT])

    size = os.path.getsize(OUT)
    print(
        f'Bundled GROK_SYSTEM_PROMPT.md → {os.path.relpath(OUT, ROOT)} '
        f'({size:,} bytes; {len(prompt):,} chars prompt, '
        f'{len(bp_json):,} chars blueprint JSON)'
    )


if __name__ == '__main__':
    main()
