#!/usr/bin/env python3
"""Bundle ui/ source files back into src/server/EmbeddedAssets.hpp.

This is the reverse of extract-ui.py. The canonical UI lives in ui/
(css/variables.css, css/style.css, js/app.js, index.html); devacos
and any instance that ships a ui/ directory on disk serves those files
directly. When avacli runs without an on-disk UI (fresh install from
.deb, no --ui-dir), it falls back to the monolithic HTML baked into
the binary via EmbeddedAssets.hpp::getIndexHtml().

Every time ui/ changes, this script must re-run so the embedded fallback
stays in sync with the on-disk sources. build.sh and
packaging/deploy-to-packages.sh invoke it automatically; run it by hand
with `python3 scripts/bundle-ui.py` if you're iterating locally.

After writing the monolithic file it invokes split_embedded_strings.py
to chop the raw string literal into <16380-char pieces so MSVC can
compile it (GCC/Clang don't care, but CI builds Windows too).
"""

import os
import re
import subprocess
import sys

try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except (AttributeError, ValueError):
    pass

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
EMBEDDED = os.path.join(ROOT, 'src', 'server', 'EmbeddedAssets.hpp')
UI_DIR = os.path.join(ROOT, 'ui')
SPLITTER = os.path.join(os.path.dirname(__file__), 'split_embedded_strings.py')

HTML_DELIM = 'html'
CSS_DELIM = 'cssv'


def read(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()


def strip_leading_block_comment(s):
    return re.sub(r'^\s*/\*.*?\*/\s*', '', s, count=1, flags=re.DOTALL)


def main():
    vars_css = read(os.path.join(UI_DIR, 'css', 'variables.css'))
    style_css = read(os.path.join(UI_DIR, 'css', 'style.css'))
    app_js = read(os.path.join(UI_DIR, 'js', 'app.js'))
    index_html = read(os.path.join(UI_DIR, 'index.html'))

    root_match = re.search(r':root\s*\{[^}]*\}', vars_css, re.DOTALL)
    if not root_match:
        sys.exit('ERROR: no :root{...} block found in ui/css/variables.css')
    root_block = root_match.group(0)
    root_inner = root_block[root_block.index('{') + 1:root_block.rindex('}')].strip()

    style_body = strip_leading_block_comment(style_css).strip()

    cdn_scripts = re.findall(
        r'<script\s+src="https?://[^"]+"></script>',
        index_html
    )
    cdn_tags = '\n'.join(cdn_scripts)

    body_match = re.search(
        r'<body>\s*(.*?)\s*<script\s+src="/ui/js/app\.js"></script>',
        index_html,
        re.DOTALL,
    )
    if not body_match:
        sys.exit('ERROR: could not locate <body>...<script src="/ui/js/app.js"> in ui/index.html')
    body_html = body_match.group(1).strip()

    html_parts = [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width,initial-scale=1,'
        'maximum-scale=1,interactive-widget=resizes-content,viewport-fit=cover">',
        '<title>Avacli</title>',
        '<style>',
        root_block,
        style_body,
        '</style>',
    ]
    if cdn_tags:
        html_parts.append(cdn_tags)
    html_parts += [
        '</head>',
        '<body>',
        body_html,
        '<script>',
        app_js.rstrip(),
        '</script>',
        '</body>',
        '</html>',
    ]
    html = '\n'.join(html_parts)

    for delim in (HTML_DELIM, CSS_DELIM):
        needle = f'){delim}"'
        if needle in html or needle in root_inner:
            sys.exit(
                f'ERROR: bundled content contains the raw-string closer {needle!r}; '
                f'pick a different delimiter in bundle-ui.py.'
            )

    out = (
        '#pragma once\n'
        '#include <string>\n'
        '\n'
        '// AUTO-GENERATED by scripts/bundle-ui.py. Do not edit this file directly.\n'
        '// Edit the canonical sources under ui/ and re-run scripts/bundle-ui.py\n'
        '// (build.sh and packaging/deploy-to-packages.sh do this for you).\n'
        '\n'
        'namespace avacli {\n'
        '\n'
        'inline std::string getCssVars() {\n'
        f'    return R"{CSS_DELIM}(\n'
        f'{root_inner}\n'
        f'){CSS_DELIM}";\n'
        '}\n'
        '\n'
        'inline std::string getIndexHtml() {\n'
        f'    return R"{HTML_DELIM}({html})'
        f'{HTML_DELIM}";\n'
        '}\n'
        '\n'
        '} // namespace avacli\n'
    )

    with open(EMBEDDED, 'w', encoding='utf-8') as f:
        f.write(out)

    subprocess.check_call([sys.executable, SPLITTER, EMBEDDED])

    size = os.path.getsize(EMBEDDED)
    print(
        f'Bundled ui/ → {os.path.relpath(EMBEDDED, ROOT)} '
        f'({size:,} bytes; {len(html):,} chars HTML, '
        f'{len(style_body):,} chars CSS, {len(app_js):,} chars JS)'
    )


if __name__ == '__main__':
    main()
